# Lifecycle
- name: 'lifecycle/active'
  color: '8fc951'
  description: 'Indicates that an issue or PR is actively being worked on by a contributor.'

- name: 'lifecycle/stale'
  color: '795648'
  description: 'Denotes an issue or PR that has become stale and will be auto-closed.'

- name: 'lifecycle/keep'
  color: 'd3e1f1'
  description: 'Denotes an issue or PR that should be preserved from going stale.'

# Size labels
- name: 'size/XS'
  color: '009900'
  description: 'Denotes a PR that changes 0-9 lines'

- name: 'size/S'
  color: '77bb02'
  description: 'Denotes a PR that changes 10-99 lines'

- name: 'size/M'
  color: 'eebb03'
  description: 'Denotes a PR that changes 100-499 lines'

- name: 'size/L'
  color: 'ee9902'
  description: 'Denotes a PR that changes 500-999 lines'

- name: 'size/XL'
  color: 'ed5500'
  description: 'Denotes a PR that changes 1000+ lines'

# Kind
- name: 'kind/design'
  color: 'c7def7'
  description: 'Categorizes issue or PR as related to design.'

- name: 'kind/documentation'
  color: 'c7def7'
  description: 'Categorizes issue or PR as related to documentation.'

- name: 'kind/feature'
  color: 'c7def7'
  description: 'Categorizes issue or PR as related to a new feature.'

- name: 'kind/enhancement'
  color: 'c7def7'
  description: 'Categorizes issue or PR as related to an improvement.'

- name: 'kind/cleanup'
  color: 'c7def7'
  description: 'Categorizes issue or PR as related to cleaning up code, process, or technical debt.'

- name: 'kind/support'
  color: 'c7def7'
  description: 'Categorizes issue or PR as support questions.'

- name: 'kind/test'
  color: 'c7def7'
  description: 'Categorizes issue or PR as related to testing.'

- name: 'kind/work-in-progress'
  color: 'c7def7'
  description: 'Categorizes issue or PR as work in progress.'

- name: 'kind/bug'
  color: 'e11d21'
  description: 'Categorizes issue or PR as related to a bug.'

- name: 'kind/regression'
  color: 'cc3333'
  description: 'Categorizes issue or PR as related to a regression from a prior release.'

# Area
- name: 'area/api'
  color: '0052cc'
- name: 'area/cli'
  color: '0052cc'
- name: 'area/test'
  color: '0052cc'
- name: 'area/auth'
  color: '0052cc'
- name: 'area/storage'
  color: '0052cc'
- name: 'area/security'
  color: '0052cc'

- name: 'area/build'
  color: '0052cc'
- name: 'area/pipeline'
  color: '0052cc'
- name: 'area/artifacts'
  color: '0052cc'
- name: 'area/platform'
  color: '0052cc'
  description: 'PR or issue related to a specific platform (OS, K8s version...)'

- name: 'area/provider/gcp'
  color: '0052cc'
- name: 'area/provider/aws'
  color: '0052cc'
- name: 'area/provider/azure'
  color: '0052cc'
- name: 'area/provider/alibaba'
  color: '0052cc'
- name: 'area/provider/vault'
  color: '0052cc'

- name: 'area/dependencies'
  color: '0052cc'

# Community
- name: 'triage/accepted'
  color: '30a14e'
  description: 'Indicates an issue or PR is ready to be actively worked on.'

- name: 'triage/duplicate'
  color: 'c31fb5'
  description: 'This issue or PR already exists.'

- name: 'triage/on-hold'
  color: 'bfa808'
  description: 'Indicates an issue or PR is on hold for some reason.'

- name: 'triage/needs-information'
  color: 'bfa808'
  description: 'Indicates an issue or PR needs more information in order to work on it.'

- name: 'triage/not-reproducible'
  color: 'bfa808'
  description: 'Indicates an issue or PR can not be reproduced as described.'

- name: 'triage/rejected'
  color: 'bfa808'
  description: 'Indicates an issue or PR that can not or will not be resolved.'

- name: 'good first issue'
  color: '7057ff'
  description: 'Good for newcomers'

# Priority
- name: 'priority/waiting'
  color: 'd4e6fd'
  description: 'Lowest priority. Possibly useful, but not yet enough support to actually get it done.'

- name: 'priority/low'
  color: 'ffdd9f'
  description: 'Issue that might be added to backlog or be rejected.'

- name: 'priority/backlog'
  color: 'ffdd9f'
  description: 'Issue that needs to be added and addressed in the backlog.'

- name: 'priority/critical'
  color: 'ff2626'
  description: 'Very critical issue that needs to be worked asap.'

- name: 'priority/longterm'
  color: 'ffa500'
  description: 'Important over the long term, but may not be worked in multiple releases'

- name: 'priority/soon'
  color: 'ffa500'
  description: 'Must be worked on either currently, or very soon, ideally for the next release'
