name: sync

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  mark-stale:
    uses: ./.github/workflows/_stale.yml
    permissions:
      issues: write
      pull-requests: write

  sync:
    uses: ./.github/workflows/_sync.yml
    permissions:
      issues: write
